name: first workflow
on: [push,workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print bye
        run: echo "good bye"
      - name: print job done
        run:  |
            echo "we are done"
            echo "finally job completed"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: checking out git repo
        uses: actions/checkout@v3

      - name: read README.md
        run: cat README.md



        
    
